### ISSUE TITLE
corpora-api no longer maintained

### ISSUE THREAD

**Issue by dipamsen** [dariusk/corpora#370]

**Comment by JKirchartz** [comment]
I've forked the [corpora-api](https://github.com/JKirchartz/corpora-api) and will work to get it running on [corpora-api.glitch.me](http://corpora-api.glitch.me/) - send me a message via one of the social networking links on [my website](https://jkirchartz.com/) and I can invite others to edit it. It's in rough shape right now because this wasn't set up for glitch.com, but after some massaging, this should be a decent solution.
